version: '3.1'

services:
  db:
    image: postgres:13.1
    privileged: true
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres_root
      POSTGRES_PASSWORD: postgres_toor
      POSTGRES_DB: todo
  backend:
    build:
      context: .
      dockerfile: ./docker/from_manual/backend/Dockerfile
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - db
  nginx:
    build:
      context: .
      dockerfile: ./docker/from_manual/nginx/Dockerfile
    ports:
      - 8000:80
    depends_on:
      - backend
  frontend:
    build:
      context: .
      dockerfile: ./docker/from_manual/frontend/Dockerfile
    ports:
      - 80:80
    depends_on:
      - nginx

